name: puppet-lint

on:
  pull_request:
    branches:
    - main
    types:
    - ready_for_review
  push:

permissions:
  contents: read

jobs:
  puppet-lint:
    if: github.event.pull_request.draft == false
    name: Run pdk validate
    runs-on: ubuntu-latest
    container:
      image: docker.io/puppet/pdk:latest
    permissions:
      contents: read # for checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate code
        run: |
          apt update
          apt install -y make gcc
          curr_loc=$(pwd)
          ERC=0
          for module in $(ls -d */)
          do
            cd ${curr_loc}/${module}
            pdk validate
            RC=$?
            if [[ $RC -ne 0 ]]
            then
              ERC=$RC
            fi
          done
          exit $ERC